Use recent forecast working directory of operational ICON runs as data source for FLEXPART-COSMO.

diff --git a/test_meteoswiss/test-fp b/test_meteoswiss/test-fp
--- a/test_meteoswiss/test-fp
+++ b/test_meteoswiss/test-fp
@@ -61,10 +61,15 @@ esac
 [[ -z $OPR_OPR_DIR ]] && source /oprusers/osm/.opr_setup_dir
 
 # Path to NWP files depending on resolution (see --resol)
-# String is split at " in: "
+# The constant-fields file is searched by adding a 'c' at the end
+# of the first filename. If not found, constant fields are assumed
+# to be contained in at least the first windfield file.
+# The source-list string is split at " in: "
 # Template:
 #   "<description> in: <file-with-path>"
-# Allowed placeholders: <yymmddhh>, <ex>, <ddhh>, <mem>
+# Allowed placeholders: <yymmddhh>, <ex>, <ddhh>, <mem>,
+# shell wildcards * and []
+# CAUTION: shell wildcard {} is not resolved, do not use!
 resolutions=()
 
 # ICON-CH1-EPS
@@ -74,9 +79,10 @@ nwp_max_range_i1=33
 lt_inc_i1=1
 nwp_source_list_i1=(
     "Operational LADM cache (interp) in: $OPR_OPR_DIR/cache/LADM/FLEXPART-I1E-CTRL/dispc*"
-    "Operational fcst cache (native) in: $OPR_OPR_DIR/cache/ICON-CH1-EPS/FCST_RING/<yymmddhh>_6<ex>/icon/<mem>/lfff<ddhh>0000{,c}"
-    "User cache                      in: $SCRATCH/<yymmddhh>_6<ex>/icon/<mem>/lfff<ddhh>0000"
-    "Cases in user store             in: $STORE/CASES/FLEXPART-I1E-CTRL/<yyyymmddhh>/dispc*"
+    "Operational fcst cache (native) in: $OPR_OPR_DIR/cache/ICON-CH1-EPS/FCST_RING/<yymmddhh>_6<ex>/icon/<mem>/lfff<ddhh>0000"
+    "Operational fcst wd    (interp) in: $OPR_OPR_DIR/wd/<yymmddhh>_6<ex>/_FXINP_lfrf<ddhh>0000_<mem>"
+    "User cache on scratch  (interp) in: $SCRATCH/flexpart/icon/<yymmddhh>_6<ex>/fxshare/_FXINP_lfrf<ddhh>0000_<mem>"
+    "User cases on store    (interp) in: $STORE/CASES/FLEXPART-I1E-CTRL/<yyyymmddhh>/dispc*"
 )
 t1_i1=3; t2_i1=9; species_no_i1=39; rel_mass_i1=2.16E4; rel_site_i1=bez # Default: opr settings
 
@@ -88,7 +94,7 @@ lt_inc_i2=1
 nwp_source_list_i2=(
     "Operational LADM cache (interp) in: $OPR_OPR_DIR/cache/LADM/FLEXPART-I2E-CTRL/dispc*"
     "Operational fcst cache (native) in: $OPR_OPR_DIR/cache/ICON-CH2-EPS/FCST_RING/<yymmddhh>_7<ex>/icon/<mem>/lfff<ddhh>0000{,c}"
-    "User cache                      in: $SCRATCH/<yymmddhh>_7<ex>/icon/<mem>/lfff<ddhh>0000"
+    "User cache on scratch           in: $SCRATCH/<yymmddhh>_7<ex>/icon/<mem>/lfff<ddhh>0000"
     "Cases in user store             in: $STORE/CASES/FLEXPART-I2E-CTRL/<yyyymmddhh>/dispc*"
 )
 t1_i2=3; t2_i2=9; species_no_i2=39; rel_mass_i2=2.16E4; rel_site_i2=bez # Default: opr settings
@@ -101,7 +107,7 @@ lt_inc_1e=1
 nwp_source_list_1e=(
     "Operational LADM cache     in: $OPR_OPR_DIR/cache/LADM/FLEXPART-C1E-CTRL/dispc*"
     "Operational fcst cache     in: arolla:$OPR_OPR_DIR/cache/COSMO-1E/FCST_RING/<yymmddhh>_4<ex>/cosmo/<mem>/lfff<ddhh>0000{,c}"
-    "User cache                 in: $SCRATCH/<yymmddhh>_4<ex>/cosmo/<mem>/lfff<ddhh>0000"
+    "User cache on scratch      in: $SCRATCH/<yymmddhh>_4<ex>/cosmo/<mem>/lfff<ddhh>0000"
     "Cases in user store        in: $STORE/CASES/FLEXPART-C1E-CTRL/<yyyymmddhh>/dispc*"
 )
 t1_1e=3; t2_1e=9; species_no_1e=39; rel_mass_1e=2.16E4; rel_site_1e=bez # Default: opr settings
@@ -114,7 +120,7 @@ lt_inc_2e=1
 nwp_source_list_2e=(
     "Operational LADM cache     in: $OPR_OPR_DIR/cache/LADM/FLEXPART-C2E/<yymmddhh>/dispc*_<mem>"
     "Operational fcst cache     in: arolla:$OPR_OPR_DIR/cache/COSMO-2E/FCST_RING/<yymmddhh>_5<ex>/cosmo/<mem>lfff<ddhh>0000{,c}"
-    "User cache                 in: $SCRATCH/<yymmddhh>_5<ex>/cosmo/<mem>/lfff<ddhh>0000"
+    "User cache on scratch      in: $SCRATCH/<yymmddhh>_5<ex>/cosmo/<mem>/lfff<ddhh>0000"
     "Cases in user store        in: $STORE/CASES/FLEXPART-C2E/<yyyymmddhh>/dispc*_<mem>"
 )
 t1_2e=3; t2_2e=9; species_no_2e=39; rel_mass_2e=2.16E4; rel_site_2e=bez # Default: opr settings
@@ -127,7 +133,7 @@ lt_inc_f=1
 nwp_source_list_f=(
     "Operational LADM cache     in: $OPR_OPR_DIR/cache/LADM/FLEXPART-IFS-EUROPE/dispf*"
     "Cases in operational store in: /store/mch/msopr/flexpart_data/test-input/ifs-europe/<yyyymmddhh>/dispf*"
-    "User cache                 in: $SCRATCH/FLEXPART-IFS-EUROPE/disp*"
+    "User cache on scratch      in: $SCRATCH/FLEXPART-IFS-EUROPE/disp*"
     "Cases in user store        in: $STORE/CASES/FLEXPART-IFS-EUROPE/<yyyymmddhh>/dispf*"
 )
 t1_f=6; t2_f=12; species_no_f=39; rel_mass_f=21.6E10; rel_site_f=cherno # Default: opr settings
@@ -139,7 +145,7 @@ nwp_max_range_g=144
 lt_inc_g=3
 nwp_source_list_g=(
     "Operational LADM cache     in: $OPR_OPR_DIR/cache/LADM/FLEXPART-IFS-GLOBAL/disp*"
-    "User cache                 in: $SCRATCH/FLEXPART-IFS-GLOBAL/disp*"
+    "User cache on scratch      in: $SCRATCH/FLEXPART-IFS-GLOBAL/disp*"
     "Cases in user store        in: $STORE/CASES/FLEXPART-IFS-GLOBAL/<yyyymmddhh>/disp*"
 )
 t1_g=0; t2_g=0; species_no_g=39; rel_mass_g=4.32E10; rel_site_g=punggye # Default: opr settings
@@ -152,7 +158,7 @@ lt_inc_1=1
 nwp_source_list_1=(
     "Operational LADM cache     in: *** no longer available ***"
     "Operational fcst ring      in: *** no longer available ***"
-    "User cache                 in: $SCRATCH/<yymmddhh>_1<ex>/lm_coarse/lfff<ddhh>0000{,c}"
+    "User cache on scratch      in: $SCRATCH/<yymmddhh>_1<ex>/lm_coarse/lfff<ddhh>0000{,c}"
     "Cases in user store        in: $STORE/CASES/COSMO-1/<yymmddhh>_1<ex>/lm_coarse/lfff<ddhh>0000{,c}"
 )
 t1_1=3; t2_1=9; species_no_1=39; rel_mass_1=2.16E4; rel_site_1=bez # Default: opr settings
@@ -165,7 +171,7 @@ lt_inc_e=1
 nwp_source_list_e=(
     "Operational LADM cache     in: *** no longer available ***"
     "Operational fcst ring      in: *** no longer available ***"
-    "User cache                 in: $SCRATCH/<yymmddhh>_2<ex>/lm_coarse/<mem>/lfff<ddhh>0000{,c}"
+    "User cache on scratch      in: $SCRATCH/<yymmddhh>_2<ex>/lm_coarse/<mem>/lfff<ddhh>0000{,c}"
     "Cases in user store        in: $STORE/CASES/COSMO-E/<yymmddhh>_2<ex>/lm_coarse/<mem>/lfff<ddhh>0000{,c}"
 )
 t1_e=3; t2_e=9; species_no_e=39; rel_mass_e=2.16E4; rel_site_e=bez # Default: opr settings
@@ -222,6 +228,8 @@ rel_lon_punggye=129.0900 ; rel_lat_punggye=41.2800 ; rel_height_punggye=100 ; re
 rel_lon_segula=178.1400  ; rel_lat_segula=52.0200  ; rel_height_segula=100  ; rel_name_segula=Segula
 # Ensemble members (-m, --member)
 member=000
+# Output gid (-O, --outgrid-tag), default: resolution (-r, --resol)
+outgrid_tag=
 # Flexpart executable path (-E, --exe-dir)
 # should agree with Makefile variable EXEDIR
 exe_dir_icon=$(dirname $PWD)/bin
@@ -281,37 +289,38 @@ Arguments:
 
 Options:
   Mandatory arguments to long options are mandatory for short options too.
-  -a, --average=H      averaging interval and output freqency of H [hours]
-                       (Default: $avg_h)
-  -n, --dry-run        print commands without executing them
-  -E, --exe-dir=DIR    Flexpart executable file path, default for
-                       - ICON: $exe_dir_icon
-                       - COSMO: $exe_dir_cosmo
-                       - IFS: $exe_dir_ifs
-  -e, --exe-name=NAME  executable file name, default: newest in DIR
-  -o, --fp-opt=OPT     add option OPT to command line when starting FLEXPART
-                       (Default: $fp_opt)
-  -h, --help           show this help and exit
-  -I, --iout=I         Set IOUT to I (1 binary, 9 NetCDF output)
-  -j, --job=NAME       manually set job name (default: consecutive number)
-  -N, --ncpus=N        numbers of cpus to allocate to OpenMP parallel run
-  -p, --partition=PART partition, one of postproc (may be abbreviated as pp),
-                       pp-serial, debug, normal, dev
-  -r, --resol=RESOL    resolution, one of: i1, i2, 1e, 2e, 1, e, f, g
-  -M, --rel-lon=LON    longitude of release
-  -M, --rel-lat=LAT    latitude of release
-  -M, --rel-mass=MASS  released mass [Bq] (default: $rel_mass)
-  -M, --rel-name=NAME  name of release site
-  -R, --rel-tag=TAG    release tag, selects file RELEASES.TAG
-  -R, --rel-site=SITE  release site, selects SITE from predefined sites
-  -t, --rel-time=T1,T2 release from T1 to T2 (lead times [hours]).
-                       (Default: $t1,$t2)
-      --run-mode=MODE  run code in MODE, one of serial or parallel
-  -S, --source-no=N    select source no N from list of NWP data sources
-  -N, --species-no=N   select species no N according to definition
-                       in SPECIES directory
-  -s, --stop           stop script before starting job (do not submit job)
-  -V, --version        output version information and exit
+  -a, --average=H       averaging interval and output freqency of H [hours]
+                        (Default: $avg_h)
+  -n, --dry-run         print commands without executing them
+  -E, --exe-dir=DIR     Flexpart executable file path, default for
+                        - ICON: $exe_dir_icon
+                        - COSMO: $exe_dir_cosmo
+                        - IFS: $exe_dir_ifs
+  -e, --exe-name=NAME   executable file name, default: newest in DIR
+  -o, --fp-opt=OPT      add option OPT to command line when starting FLEXPART
+                        (Default: $fp_opt)
+  -h, --help            show this help and exit
+  -I, --iout=I          Set IOUT to I (1 binary, 9 NetCDF output)
+  -j, --job=NAME        manually set job name (default: consecutive number)
+  -N, --ncpus=N         numbers of cpus to allocate to OpenMP parallel run
+  -O, --outgrid-tag=TAG output grid tag, selects file OUTGRID.TAG
+  -p, --partition=PART  partition, one of postproc (may be abbreviated as pp),
+                        pp-serial, debug, normal, dev
+  -r, --resol=RESOL     resolution, one of: i1, i2, 1e, 2e, 1, e, f, g
+  -M, --rel-lon=LON     longitude of release
+  -M, --rel-lat=LAT     latitude of release
+  -M, --rel-mass=MASS   released mass [Bq] (default: $rel_mass)
+  -M, --rel-name=NAME   name of release site
+  -R, --rel-tag=TAG     release tag, selects file RELEASES.TAG
+  -R, --rel-site=SITE   release site, selects SITE from predefined sites
+  -t, --rel-time=T1,T2  release from T1 to T2 (lead times [hours]).
+                        (Default: $t1,$t2)
+      --run-mode=MODE   run code in MODE, one of serial or parallel
+  -S, --source-no=N     select source no N from list of NWP data sources
+  -N, --species-no=N    select species no N according to definition
+                        in SPECIES directory
+  -s, --stop            stop script before starting job (do not submit job)
+  -V, --version         output version information and exit
 
 EOF
 } # function usage
@@ -427,6 +436,14 @@ while (( $# > 0 )) ; do
                 fp_opt="${1#*=}"
             else
                 (( $# > 1 )) && shift && fp_opt="$1"
+            fi
+            ;;
+        -O | --outgrid-tag*)
+            # Mandatory option argument with or without =
+            if [[ "$1" == *=* ]] ; then
+                outgrid_tag="${1#*=}"
+            else
+                (( $# > 1 )) && shift && outgrid_tag="$1"
             fi
             ;;
         -p | --partition*)
@@ -609,7 +626,7 @@ if [[ -z $source_no ]] ; then
     source_no=$REPLY
 else
     (( i_source = $source_no - 1 ))
-    answer=${nwp_source_list[$i_source]}
+    answer="${nwp_source_list[$i_source]}"
 fi
 # Extract description and file path from nwp_source_list entry, splitting at "in:"
 source_desc="${answer%in:*}"
@@ -667,6 +684,10 @@ if [[ -z $exe_name ]] ; then
     # Select newest from exe_dir
     echo $tag: "Looking for newest FLEXPART executable in: $exe_dir"
     exe_list=( $(ls -t $exe_dir/FLEXPART*) )
+    if (( $? )) ; then
+        echo $tag: "No executable found: $exe_dir/FLEXPART*"
+        exit 6
+    fi
     exe_name=$(basename ${exe_list[0]%.env})
     echo -n $tag: "Found: "
     ls -l $exe_dir/$exe_name
@@ -823,7 +844,7 @@ nwp_search=$(echo "$nwp_source" \
 # Check if NWP data is available
 nwp_files=( $nwp_search )
 nwp_dir=$(dirname $nwp_files)
-if [ ! -f $nwp_files ] ; then
+if [[ ! -f $nwp_files ]] ; then
     echo $tag: "%ERROR: No matching files found: $nwp_files"
     if [[ $nwp_files == /opr/* && $HOSTNAME != arolla* ]] ; then
         echo $tag: "For current data on /opr try on arolla"
@@ -839,11 +860,11 @@ fi
 
 # Check if GRIB constant data available
 if [[ $nwp_files != *disp* ]] ; then
-    # Forecast files, assuming COSMO forecasts
-    grib_const_file=lfff00000000c
-    if [ ! -f $nwp_dir/$grib_const_file ] ; then
-        echo $tag: "Constant GRIB data not available in: $nwp_dir"
-        exit 1
+    # Forecast files, file with constant fields needed
+    grib_const_file=${nwp_files}c
+    if [[ ! -f $grib_const_file ]] ; then
+        echo $tag: "WARNING: Constant GRIB data file not found: $grib_const_file"
+        unset grib_const_file
     fi
 fi
 
@@ -852,7 +873,7 @@ echo $tag: "NWP data source: $nwp_dir contains ${#nwp_files[*]} files"
 
 # NWP input data location for flexpart
 grib_input=$start_location/grib
-if [ -d $grib_input ] ; then
+if [[ -d $grib_input ]] ; then
     echo $tag: "Using existing NWP data directory: $grib_input"
 else
     echo $tag: "Creating NWP data directory: $grib_input"
@@ -870,7 +891,7 @@ if (( ${#nwp_files[*]} > $fc_range - $t1 )) ; then
         # only first [0] and last [-1] array element
         $exe_cmd cp -sf ${nwp_files[0]}...${nwp_files[-1]} $grib_input
     fi
-    [[ -n $grib_const_file ]] && $exe_cmd cp -sf $nwp_dir/$grib_const_file $grib_input
+    [[ -n $grib_const_file ]] && $exe_cmd cp -sf $grib_const_file $grib_input
 else
     echo $tag: "ERROR(4): Insufficient number of files: ${#nwp_files[*]}"
     exit 8
@@ -905,13 +926,29 @@ YYYYMMDD HHMISS
 ________ ______      __________________
 EOF
 
+    # Add grib file with constant fields if available
+    # Format see readavailable.f90 line read(unitavailab,...)
+    # '(i8,1x,i6,2(6x,a32))'
+    avail_fmt='%8s %6s      %s\n'
+    if [[ -n grib_const_file ]] ; then
+        printf "$avail_fmt" \
+            0 999999 $(basename $grib_const_file) >> \
+            $available_file
+    fi
+
+
     # Find grib files
     if [ -d $grib_input ] ; then
         pushd $grib_input > /dev/null
         gribfiles=( $nest* )
         if (( ${#gribfiles[*]} < 2)) ; then
             echo $tag: "No $nest* files found in: $grib_input"
-            unset gribfiles
+            echo $tag: "Use other files (no nesting possible)"
+            gribfiles=( $(basename "$nwp_search") )
+            if (( ${#gribfiles[*]} < 2)) ; then
+                echo $tag: "No files found: $grib_input/$nwp_search"
+                unset gribfiles
+            fi
         fi
         popd > /dev/null
     else
@@ -924,9 +961,18 @@ EOF
             echo $tag: "WARNING: Broken link found and removed in NWP input data direcory: $grib_input/$grib_file"
             rm $grib_input/$grib_file
         else
-            printf "%s %s0000      %s\n" \
-                ${grib_file:5:8} ${grib_file:13:2} $grib_file >> \
-                $available_file
+            if [[ $grib_file == disp* ]] ; then
+                # Extract valid date/time from filename
+                printf "$avail_fmt" \
+                    ${grib_file:5:8} ${grib_file:13:2}0000 $grib_file >> \
+                    $available_file
+            else
+                # Extract valid date/time with grins
+                vdate=$(grins --vdate --number=1 $grib_input/$grib_file)
+                printf "$avail_fmt" \
+                    ${vdate:8:8} ${vdate:16:4}00 $grib_file >> \
+                    $available_file
+            fi
         fi
     done
 
@@ -981,7 +1027,11 @@ $exe_cmd cp $input_templates/SPECIES/* $flex_input/SPECIES
 
 # Namelist template files
 command=COMMAND
-outgrid=OUTGRID.$resol
+if [[ -n $outgrid_tag ]] ; then
+    outgrid=OUTGRID.$outgrid_tag
+else
+    outgrid=OUTGRID.$resol
+fi
 
 # Link landuse source
 eval landuse_source=\$landuse_source_$nwp_model
@@ -1007,7 +1057,7 @@ fi
 
 # Command
 [[ -z $exe_cmd ]] && echo -n " $command --> COMMAND,"
-if [ -f $input_templates/$command ] ; then
+if [[ -f $input_templates/$command ]] ; then
     $exe_cmd cp $input_templates/$command $flex_input/COMMAND
 else
     echo
@@ -1018,7 +1068,7 @@ fi
 
 # Outgrid
 [[ -z $exe_cmd ]] && echo -n " $outgrid --> OUTGRID"
-if [ -f $input_templates/$outgrid ] ; then
+if [[ -f $input_templates/$outgrid ]] ; then
     $exe_cmd cp $input_templates/$outgrid $flex_input/OUTGRID
 else
     echo
@@ -1242,7 +1292,7 @@ logline="$0 $args # $tag $basetime $fc_range $mode"
 logline+=" --average=$avg_h --exe-dir=$exe_dir --exe-name=$exe_name"
 logline+=" --job=$job_name"
 [[ $run_mode == parallel ]] && logline+=" --ncpus=$ncpus"
-logline+=" --partition=$partition"
+logline+=" --outgrid-tag=$outgrid_tag --partition=$partition"
 logline+=" --rel-mass=$rel_mass --rel-tag=$rel_tag --rel-time=$t1,$t2 --rel-site=$rel_site"
 logline+=" --resol=$resol --run-mode=$run_mode"
 logline+=" --species-no=$species_no"
